import { SessionProvider } from "next-auth/react";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        {/* <SessionProvider> */}
        {children}
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
